package com.milkmitra.dao;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import com.milkmitra.model.Farmer;
import  com.milkmitra.utils.DBConnection; // we can write import static com.milkmitra.utils.DBConnection; if we want direct access of openConnection.

public class FarmerDaoImpl implements IFarmerDao 
{
	
	// -----> Steps for implementation class....
	
	//Step 1. --> get instance of connection class...
	//Step 2. --> Create Instance Variable of Prepared Statement / Statement / Stored Procedures..
	//Step 3. --> Create Constructor of Implementation class(Because as of our design we will make ready of prepared statements)
	
	private Connection cn;
	private PreparedStatement pst1, pst2, pst3, pst4, pst5, pst6, pst7;
	
	public FarmerDaoImpl() throws ClassNotFoundException, Exception
	{
		//cn = openConnection();
		cn = DBConnection.openConnection();
		
		// 1. --> Adding Farmer --logic(first inserting farmer details then generating farmerCode after retrieving farmerId)
		//farmer_id | mpp_code | farmer_code | farmer_name | mobile | email | address | account_holder_name | bank_account_no | ifsc_code
		//bank_name |  andhar_number | joining_date | is_active
		String sql = "insert into farmers values(default,?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
		pst1 = cn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
		
		String sql2 = "update farmers set farmer_code=? where farmer_id=?";
		pst2 = cn.prepareStatement(sql2);
		
		//2. --> Deactivating Farmers 
		//farmerCode
		String sql3 = "update farmers set is_active = 0 where farmer_code = ? and is_active = 1";
		pst3 = cn.prepareStatement(sql3);
		
		//3. --> View Farmers(All Farmers)
		String sql4 = "select farmer_code, farmer_name, mobile, joining_date, is_active from farmers";
		pst4 = cn.prepareStatement(sql4);
		
		//4. --> View Farmer Details
		String sql5 = "select * from farmers where farmer_code = ?";
		pst5 = cn.prepareStatement(sql5);
		
		//5. --> Edit Farmer Details
		String sql6 = "update farmers set farmer_name=?, mobile=?,email=?,address=?,account_holder_name=?,bank_account_no=?,ifsc_code=?,bank_name=?,  andhar_number=? where farmer_code = ?";
		pst6 = cn.prepareStatement(sql6);
		
		//6. --> Reactivate Farmer
		String sql7 = "update farmers set is_active = 1 where farmer_code = ? and is_active = 0";
		pst7 = cn.prepareStatement(sql7);
	}
	

	@Override
	public String addFarmer(Farmer farmer) throws SQLException {
		// TODO Auto-generated method stub
		
		//pst1.setString(0, farmer.getFarmerId); --> because farmer id will be generated by sql itself..
		//pst1.setString(1, farmer.getFarmerCode); --> because farmer code will be generated bysql itself..
		pst1.setString(1, farmer.getMppCode());
		pst1.setNull(2, java.sql.Types.VARCHAR);
		pst1.setString(3, farmer.getFarmerName());
		pst1.setString(4, farmer.getMobile());
		pst1.setString(5, farmer.getEmail());
		pst1.setString(6, farmer.getAddress());
		pst1.setString(7, farmer.getAccountHolderName());
		pst1.setString(8, farmer.getAccountNo());
		pst1.setString(9, farmer.getIfscCode());
		pst1.setString(10, farmer.getBankName());
		pst1.setString(11, farmer.getAndharNo());
		pst1.setDate(12, Date.valueOf(farmer.getJoiningDate()));
		pst1.setBoolean(13, farmer.isActive());
		
		int updateCount = pst1.executeUpdate();
		
		if(updateCount == 1)
		{
			ResultSet rs = pst1.getGeneratedKeys();

		    if(rs.next())
		    {
		        int farmerId = rs.getInt(1);

		        System.out.println("Generated Farmer Id = "+ farmerId);
		        
		        String farmerCode = String.format("F%03d", farmerId);
		        
		        farmer.setFarmerCode(farmerCode);
		        
		        pst2.setString(1, farmerCode);
		        pst2.setInt(2, farmerId);

		        int count = pst2.executeUpdate();
		        
		        	if(count == 1)
		        	{
		        		return farmerCode;
		        	}
		    }
		}
		
		return null;
	}
	
	@Override
	public int deactivateFarmer(String farmerCode) throws SQLException {
		
		pst3.setString(1, farmerCode);
		int updateCount = pst3.executeUpdate();
		
		if(updateCount == 1)
		{
			return 1;
		}
		else
		
			return 0;
	}
	
	@Override
	public List<Farmer> getAllFarmers() throws SQLException
	{
		// TODO Auto-generated method stub
		List<Farmer> farmers = new ArrayList<>();
		
		try(ResultSet rst=pst4.executeQuery())
		{
			while(rst.next())
			{
				//farmer_code, farmer_name, mobile, joining_date
				farmers.add(new Farmer(rst.getString(1), rst.getString(2), rst.getString(3), rst.getDate(4).toLocalDate(), rst.getBoolean(5)));
			}
		}
		
		return farmers;
	}
	
	@Override
	public Farmer getFarmerDetails(String farmerCode) throws SQLException
	{
		//System.out.println("DaoImpl Called....");
		
		pst5.setString(1, farmerCode);
		
		 try(ResultSet rs = pst5.executeQuery())
		    {
		        if(rs.next())
		        {
		            Farmer farmer = new Farmer();
		            
		          //farmer_id |  mpp_code | farmer_code | farmer name | mobile | email | address | account holder name | bank account no | ifsc code
		        	//bank_name | aadhaar_no | joining_date | is_active
		            
		            farmer.setFarmerId(rs.getInt("farmer_id"));
		            farmer.setMppCode(rs.getString("mpp_code"));
		            farmer.setFarmerCode(rs.getString("farmer_code"));
		            farmer.setFarmerName(rs.getString("farmer_name"));
		            farmer.setMobile(rs.getString("mobile"));
		            farmer.setEmail(rs.getString("email"));
		            farmer.setAddress(rs.getString("address"));
		            farmer.setAccountHolderName(rs.getString("account_holder_name"));
		            farmer.setAccountNo(rs.getString("bank_account_no"));
		            farmer.setIfscCode(rs.getString("ifsc_code"));
		            farmer.setBankName(rs.getString("bank_name"));
		            farmer.setAndharNo(rs.getString("andhar_number"));
		            farmer.setJoiningDate(rs.getDate("joining_date").toLocalDate());
		            farmer.setActive(rs.getBoolean("is_active"));

		            return farmer;
		        }
		    }
		 	return null;
	}
	
	@Override
	public int editFarmerDetails(Farmer farmer) throws SQLException
	{
		//farmer name | mobile | email | address | account holder name | bank account no | ifsc code
    	//bank_name | aadhaar_no | farmer_code
		pst6.setString(1, farmer.getFarmerName());
		pst6.setString(2, farmer.getMobile());
		pst6.setString(3, farmer.getEmail());
		pst6.setString(4, farmer.getAddress());
		pst6.setString(5, farmer.getAccountHolderName());
		pst6.setString(6, farmer.getAccountNo());
		pst6.setString(7, farmer.getIfscCode());
		pst6.setString(8, farmer.getBankName());
		pst6.setString(9, farmer.getAndharNo());
		pst6.setString(10, farmer.getFarmerCode());
		
		int updateCount = pst6.executeUpdate();
		
		if(updateCount == 1)
		{
			System.out.println("Farmer Details Updated Sucessfully..");
			return 1;
		}
		else
		{
			return 0;
		}	
	}
	
	@Override
	public int reactivateFarmer(String farmerCode) throws SQLException
	{
		pst7.setString(1, farmerCode);
		int updateCount = pst7.executeUpdate();
		
		if(updateCount == 1)
		{
			System.out.println("Farmer Reactivated Sucessfully");
			return 1;
		}
		else
		
			return 0;
	}
	
	
	
	//Connection Cleaning...
	public void cleanUp() throws SQLException
	{
		if(pst1 != null)
			pst1.close();
		if(pst2 != null)
			pst2.close();
		if(pst3 != null)
			pst3.close();
		if(pst4 != null)
			pst4.close();
		if(pst5 != null)
			pst5.close();
		if(pst6 != null)
			pst6.close();
		if(pst7 != null)
			pst7.close();
		if(cn != null)
			cn.close();
		System.out.println("Farmer dao cleaned up!!");
		
	}


	
}
