package com.milkmitra.dao;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import com.milkmitra.model.Collection;
import com.milkmitra.utils.DBConnection;

public class MilkCollectionDaoImpl implements IMilkCollectionDao {
	private Connection cn;
	private PreparedStatement pst1, pst2, pst3;

	public MilkCollectionDaoImpl() throws ClassNotFoundException, Exception {
		// cn = openConnection();
		cn = DBConnection.openConnection();

		// collectionId | farmerCode | collectionDate | shift | milkType
		// quantity | fat | snf | amount | ratePerLtr
		// isActive | createdAt

		// 1. Inserting Milk Collection Data
		String sql = "insert into milkcollection values(default,?, ?, ?, ?, ?, ?, ?, ?, ?, ?, default)";
		pst1 = cn.prepareStatement(sql);

	}

	@Override
	public String addCollection(Collection collection) throws SQLException {
		// steps
		// 1. Set all values in preparedStatement from servlet
		// 2. Execute Query
		// 3. Return Message For Sucessful or Unsucessful entry

		// pst1.setString(1, farmer.getCollectionId); --> because farmer code will be
		// generated bysql itself..
		pst1.setString(1, collection.getFarmerCode());
		pst1.setDate(2, Date.valueOf(collection.getCollectionDate()));
		pst1.setString(3, collection.getShift());
		pst1.setString(4, collection.getMilkType());
		pst1.setDouble(5, collection.getQuantity());
		pst1.setDouble(6, collection.getFat());
		pst1.setDouble(7, collection.getSnf());
		pst1.setDouble(8, collection.getAmount());
		pst1.setDouble(9, collection.getRatePerLtr());
		pst1.setBoolean(10, collection.isActive());

		int updateCount = pst1.executeUpdate();

		if (updateCount == 1) {
			return "Collection Saved Successfully";
		}
		return null;
	}

	public void cleanUp() throws SQLException {
		if (pst1 != null)
			pst1.close();
		if (cn != null)
			cn.close();

		System.out.println("Milk Collection Dao Cleaned Up!!");
	}

}
